services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: le_xot
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: lists
    ports:
      - '6543:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  admin:
    image: adminer
    restart: unless-stopped
    depends_on: 
      - postgres
    ports:
      - 54321:8080
volumes:
  pgdata:
